### ISSUE TITLE
Custom icon HeaderAction node (UISHell) send SSR error

### ISSUE THREAD

**Issue by myangga** [IBM/carbon-components-svelte#371]
Using: Sapper v0.28.10 + Carbon-svelte v 0.21
[https://carbon-svelte.vercel.app/components/UIShell](https://carbon-svelte.vercel.app/components/UIShell)

Trying to insert custom icon (Notification20) on HeaderAction component (UISHell) is throwing following error:
```shell
Error: <svelte:component this={...}> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules
    at validate_component (/Users/mikael/Sources/carbon/__sapper__/dev/server/server.js:321:15)
    at /Users/mikael/Sources/carbon/__sapper__/dev/server/server.js:665:7
    at Object.$$render (/Users/mikael/Sources/carbon/__sapper__/dev/server/server.js:339:22)
    at /Users/mikael/Sources/carbon/__sapper__/dev/server/server.js:794:265
    at Object.$$render (/Users/mikael/Sources/carbon/__sapper__/dev/server/server.js:339:22)
    at Object.default (/Users/mikael/Sources/carbon/__sapper__/dev/server/server.js:1432:55)
    at /Users/mikael/Sources/carbon/__sapper__/dev/server/server.js:1029:103
    at Object.$$render (/Users/mikael/Sources/carbon/__sapper__/dev/server/server.js:339:22)
    at Object.default (/Users/mikael/Sources/carbon/__sapper__/dev/server/server.js:1421:59)
    at /Users/mikael/Sources/carbon/__sapper__/dev/server/server.js:714:34
```

And here is my layout svelte file to reproduce:
```svelte
<script>
	import "carbon-components-svelte/css/all.css";
	import {
		Header,
		HeaderUtilities,
		HeaderAction,
		HeaderActionSearch,
		HeaderGlobalAction,
		HeaderPanelLinks,
		HeaderPanelDivider,
		HeaderPanelLink,
		SideNav,
		SkipToContent,
		Content,
		Grid,
		Row,
		Column,
	} from "carbon-components-svelte";
	import SettingsAdjust20 from "carbon-icons-svelte/lib/SettingsAdjust20";
	import Notification20 from "carbon-icons-svelte/lib/Notification20";
	import Nav from '../components/Nav.svelte';

	export let segment;
	let isSideNavOpen = false;
  	let isOpen = false;
</script>

<style></style>

<Header company="IBM" platformName="Carbon Svelte" bind:isSideNavOpen>
	<div slot="skip-to-content">
	  <SkipToContent />
	</div>
	<HeaderUtilities>
	  <HeaderActionSearch />
	  <HeaderGlobalAction aria-label="Settings" icon={SettingsAdjust20} />
	  <HeaderAction aria-label="Notifications" icon={Notification20} bind:isOpen>
		<HeaderPanelLinks>
		  <HeaderPanelDivider>Switcher subject 1</HeaderPanelDivider>
		  <HeaderPanelLink>Switcher item 1</HeaderPanelLink>
		  <HeaderPanelDivider>Switcher subject 2</HeaderPanelDivider>
		  <HeaderPanelLink>Switcher item 1</HeaderPanelLink>
		  <HeaderPanelLink>Switcher item 2</HeaderPanelLink>
		  <HeaderPanelLink>Switcher item 3</HeaderPanelLink>
		  <HeaderPanelLink>Switcher item 4</HeaderPanelLink>
		  <HeaderPanelLink>Switcher item 5</HeaderPanelLink>
		</HeaderPanelLinks>
	  </HeaderAction>
	</HeaderUtilities>
  </Header>
  
  <SideNav bind:isOpen={isSideNavOpen}>
	<Nav {segment}/>
  </SideNav>
  
  <Content>
	<slot></slot>
  </Content>
```

Thanks for support

**Comment by metonym** [comment]
The `HeaderAction` API is a bit different compared to other uses of the `icon` prop.

Could you try the following?

```diff
- <HeaderAction aria-label="Notifications" icon={Notification20} bind:isOpen>
+ <HeaderAction aria-label="Notifications" icon={{ render: Notification20 } bind:isOpen>
```

**Comment by myangga** [comment]
> The `HeaderAction` API is a bit different compared to other uses of the `icon` prop.
> 
> Could you try the following?
> 
> ```diff
> - <HeaderAction aria-label="Notifications" icon={Notification20} bind:isOpen>
> + <HeaderAction aria-label="Notifications" icon={{ render: Notification20 } bind:isOpen>
> ```

**Opps!! Definitely do the job. Many thanks.**

```svelte
  /**
   * Specify the icon props
   * @type {{ render: typeof import("carbon-icons-svelte/lib/Add16").default; skeleton: boolean; }} [icon]
   */
  export let icon = undefined;
```
