### ISSUE TITLE
[FEATURE REQUEST] TypeScript support

### ISSUE THREAD

**Issue by silvioprog** [IBM/carbon-components-svelte#555]
It would be nice to provide TypeScript support.

If you try to apply TS using the official steps [published at Sapper page](https://sapper.svelte.dev/docs#Getting_started), it raises the following error:

```
C:\svelte-app>node scripts/setupTypeScript.js
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'C:\svelte-app\scripts\setupTypeScript.js'
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:725:27)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)←[39m
←[90m    at internal/main/run_main_module.js:17:47←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: []
}
```

cheers

**Comment by metonym** [comment]
This project has [offered TypeScript definitions](https://github.com/IBM/carbon-components-svelte/tree/master/types) for almost 5 months now.

**Comment by silvioprog** [comment]
I accidentally forgot to inform the link of the project, which is related to Carbon Components Svelte: https://github.com/IBM/carbon-components-svelte/tree/master/examples/sapper.

Edited the issue summary above.

**Comment by metonym** [comment]
Closing since [Sapper](https://github.com/sveltejs/sapper) was deprecated over half a year ago.
